apiVersion: v1
kind: Namespace
metadata:
  name: garda
  labels:
    apps: oauth
  annotations:
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: garda
  namespace: garda
  labels:
    app: garda
    platform: oauth
    release: '0.1'
  annotations:
    env: dev
    monitoring: 'true'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: garda
  template:
    metadata:
      labels:
        app: garda
    spec:
      volumes:
        - name: garda-vol
          persistentVolumeClaim:
            claimName: garda-claim
      containers:
        - image: "registry.tassesforce.com:5000/garda"
          imagePullPolicy: Always
          name: garda
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: garda
  name: garda-service
  namespace: garda
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: garda
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: garda-ingress
  namespace: garda
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 
      http:
        paths:
        - path: /auth
          backend:
            serviceName: garda-service
            servicePort: 80
        - path: /token
          backend:
            serviceName: garda-service
            servicePort: 80
